In [1]:
import pandas as pd
import numpy as np
from scipy import stats
stats.chi2.ppf(0.99,6)

16.811893829770927

In [2]:
data=pd.read_excel('C:/Users/Mahendran/Downloads/nptel-DA/acad.xlsx')
data

Rsp No  aa  pe  sm  ae  r  g  c
0        1  99  19   1   2  0  0  1
1        2  46  12   0   0  0  0  0
2        3  57  15   1   1  0  0  0
3        4  94  18   2   2  1  1  1
4        5  82  13   2   1  1  1  1
5        6  59  12   0   0  2  0  0
6        7  61  12   1   2  0  0  0
7        8  29   9   0   0  1  1  0
8        9  36  13   1   1  0  0  0
9       10  91  16   2   2  1  1  0
10      11  55  10   0   0  1  0  0
11      12  58  11   0   1  0  0  0
12      13  67  14   1   1  0  1  1
13      14  77  14   1   2  2  1  0
14      15  71  12   0   0  2  1  0
15      16  83  16   2   2  1  0  1
16      17  96  15   2   2  2  0  1
17      18  87  12   1   1  0  0  1
18      19  62  11   0   0  0  0  0
19      20  52   9   0   1  2  1  0
20      21  46  10   1   0  0  1  0
21      22  91  20   2   2  1  0  0
22      23  85  12   2   1  1  1  1
23      24  48  11   1   1  2  0  0
24      25  81  17   1   1  1  1  1
25      26  74  16   2   1  2  1  0
26      27  68  12   2   1  1  1  1
27      28  63  12   1   0  0  0  1
28      29  72  14   0   2  0  0  0
29      30  99  19   1   1  1  0  0
30      31  64  13   1   1  0  0  0
31      32  77  13   1   0  1  1  1
32      33  88  16   2   2  0  1  0
33      34  54   9   0   1  1  0  0
34      35  86  17   1   2  1  0  1
35      36  73  15   1   1  0  1  0
36      37  79  15   2   1  0  0  1
37      38  85  14   2   1  2  1  1
38      39  96  16   0   1  1  0  1
39      40  59  12   1   0  0  1  0
40      41  84  14   1   0  1  0  1
41      42  71  15   2   1  1  0  0
42      43  89  15   0   1  0  1  1
43      44  38  12   1   0  1  1  0
44      45  62  11   1   1  2  0  1
45      46  93  16   1   0  1  0  1
46      47  71  13   2   1  1  0  0
47      48  55  11   0   1  0  0  0
48      49  74  15   1   2  0  1  0
49      50  76  20   0   1  1  0  1

In [8]:
pivot=pd.pivot_table(data[['sm','g']],index='g',columns='sm',aggfunc=len)
pivot

sm   0   1  2
g            
0   10  13  6
1    4   9  8

In [9]:
from scipy.stats import chi2_contingency

In [10]:
chi2,p,df,tb=chi2_contingency(pivot)

In [11]:
chi2,p,df

(2.3649585225939904, 0.3065178579178871, 2)

In [17]:
np.sum(data['sm']),np.sum(data.loc[0])

(50, 123)

In [12]:
tb

array([[ 8.12, 12.76,  8.12],
       [ 5.88,  9.24,  5.88]])

# Goodness of fit Test

find poisson distribution follows below dataset

In [18]:
data1=pd.read_excel('C:/Users/Mahendran/Downloads/nptel-DA/P_distribution.xlsx')
data1

Arrivals  Frequency
0          0          0
1          1          1
2          2          4
3          3         10
4          4         14
5          5         20
6          6         12
7          7         12
8          8          9
9          9          8
10        10          6
11        11          3
12        12          1

In [28]:
total_time_period=np.sum(data1['Frequency'])
total_time_period

100

In [29]:
total_arrival=np.sum(data1['Frequency']*data1['Arrivals'])
total_arrival

600

In [31]:
mu=np.divide(total_arrival,total_time_period)
mu

6.0

In [34]:
obs_freq=data1['Frequency']
exp_freq=[]#n*f(x) where f(x) = to poisson function
for i in range(len(obs_freq)):
    e_freq=100*stats.poisson.pmf(i,mu)
    exp_freq.append(e_freq)
exp_freq

[0.24787521766663584,
 1.4872513059998145,
 4.461753917999444,
 8.923507835998894,
 13.385261753998332,
 16.062314104797995,
 16.06231410479801,
 13.767697804112569,
 10.32577335308442,
 6.883848902056284,
 4.130309341233764,
 2.2528960043093247,
 1.1264480021546681]

In [35]:
np.round(exp_freq)

array([ 0.,  1.,  4.,  9., 13., 16., 16., 14., 10.,  7.,  4.,  2.,  1.])

In [38]:
#we two digit after so we use 
exp_freq_roun=np.round(exp_freq,2)
exp_freq_roun

array([ 0.25,  1.49,  4.46,  8.92, 13.39, 16.06, 16.06, 13.77, 10.33,
        6.88,  4.13,  2.25,  1.13])

In [49]:
daf=pd.DataFrame(zip(obs_freq,exp_freq_roun),columns=['observed frequency','expected frequency'])
daf

observed frequency  expected frequency
0                    0                0.25
1                    1                1.49
2                    4                4.46
3                   10                8.92
4                   14               13.39
5                   20               16.06
6                   12               16.06
7                   12               13.77
8                    9               10.33
9                    8                6.88
10                   6                4.13
11                   3                2.25
12                   1                1.13

In [51]:
# exp freq not less than 5 so add row whose value less than 5 ntill greater than 5
obs_freq=[5,10,14,20,12,12,9,8,10]
exp_freq=[6.20,8.92,13.39,16.06,16.06,13.77,10.33,6.88,8.39]
stats.chisquare(obs_freq,exp_freq)

Power_divergenceResult(statistic=3.2738182931105193, pvalue=0.916017731732134)

In [53]:
stats.chi2.ppf(0.95,7)

14.067140449340169

find below dataset follows uniform distribution

In [54]:
stats.chi2.ppf(0.99,11)

24.724970311318277

In [57]:
x=[1610,1585,1649,1590,1540,1397,1410,1350,1495,1564,1602,1655]
np.mean(x)

1537.25

In [58]:
exp_f=[]
for i in range(len(x)):
    exp_f.append(1537.25)
exp_f

[1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25,
 1537.25]

In [59]:
stats.chisquare(x,exp_f)

Power_divergenceResult(statistic=74.37583346885673, pvalue=1.78545252783034e-11)

find the below dataset follow normal distribution

In [63]:
a=[33,43,44,45,52,52,56,58,63,64,64,65,66,68,70,72,73,73,74,75,83,84,85,86,91,92,94,98,102,105]
len(a)

30

In [65]:
mean=np.mean(a)
std=np.std(a)
mean,std

(71.0, 18.226354544998845)

In [67]:
x=1/6
for j in range(1,6):
    prob_intervals=stats.norm.ppf(j*x,mean,std)
    print(prob_intervals)

53.36743154175236
63.14941153083116
71.0
78.85058846916884
88.63256845824763


In [69]:
30/6 # exp_freq greater or = to 5 so 30 is div by 6 no of intervals 6

5.0

In [70]:
exp_f=[5,5,5,5,5,5]
obs_f=[6,3,6,5,4,6]
stats.chisquare(obs_f,exp_f)

Power_divergenceResult(statistic=1.5999999999999999, pvalue=0.9012493445012737)

In [71]:
stats.chi2.ppf(0.95,3)

7.814727903251179